### ISSUE TITLE
Sms bomb tüm siteleri deneyince baştan başlamıyor

### ISSUE THREAD

**Issue by valco72** [tingirifistik/Enough#11]
Mesela sms sayısını 100 yapınca tüm smsleri gönderiyor ama baştan başlayıp ilk siteden tekrar denemiyor. Bunu ekleyemez miyiz?

**Comment by tingirifistik** [comment]
53 servis var şu an. Gönderilecek sms sayısı servis sayısını geçiyorsa, gönderilen sms sayısı istenilen miktara eşit olana kadar her servisi birkaç kere kullanılır. Yani baştan başlar.

**Comment by valco72** [comment]
Ama başlamıyor. Hatta arada bir tıkanıyor ve direkt sms gelmiyor

**Comment by valco72** [comment]
Madamecoco sms gonderdikten sonra tıkanıyor hocam @tingirifistik

**Comment by valco72** [comment]
Hocam kusura bakma biraz gecikmeli de olsa gönderiyormuş baya gecikiyor ama geliyor. Kapatıyorum konuyu
