### ISSUE TITLE
yardımcı olabilirsen mutlu olurum

### ISSUE THREAD

**Issue by Kaosw2** [tingirifistik/Enough#13]
bende arama kısmı hiç çalışmıyo ve bu dc botu için yardımcı olabilirmisin

**Comment by lotryn** [comment]
Discord Verirmisiniz Daha iyi yardımcı olabilmek için

**Comment by Kaosw2** [comment]
hENNESsy#8726

**Comment by tingirifistik** [comment]
Arama kısmı çok iyi olmadı. Arama kısmını geliştireceğim zamanla.
