### ISSUE TITLE
Merhaba Açıklamayı Turkey Yerine Turkiye Olarak Değiştirirmisiniz

### ISSUE THREAD

**Issue by lotryn** [tingirifistik/Enough#16]
Merhaba Açıklamayı Turkey Yerine Turkiye Olarak Değiştirirmisiniz

**Comment by tingirifistik** [comment]
![türk-kurt-kurt](https://user-images.githubusercontent.com/51286195/213909918-43e295ff-c585-4316-87b9-6748dd8d771d.gif)
