### ISSUE TITLE
Birden fazla numara özelliği çalışmıyor.

### ISSUE THREAD

**Issue by Bora185** [tingirifistik/Enough#24]
Dosya dizini sorulduğunda girdiğim dosyadaki hiçbir numaraya SMS gitmiyor. 3 tane numara yazdım alt alta hiçbirine gitmedi. Özelliğin çalışan halini pull request olarak attım.

**Comment by Bora185** [comment]
tamam hallettim.

**Comment by tingirifistik** [comment]
Bir sorun yok değil mi?

**Comment by Bora185** [comment]
Hayır, numaraları txt dosyasına yanlış yazmışım. 1-2 kere denedim olmayınca dosyayı kontrol etmeden konu açtım. Sonradan aklıma geldi dosyaya bakmak.
