### ISSUE TITLE
Sms bomber kurulum

### ISSUE THREAD

**Issue by Kadirmertabdulharim** [tingirifistik/Enough#25]
Selamlar Ustacım Sms bomber kurulumu hakkında yazıyorum Kurulumu tam olarak bir şekilde nasıl yapıyoruz Python aracılığıyla teşekkürler.
@Bora185 @tingirifistik

**Comment by Bora185** [comment]
İşletim sistemin nedir dostum?

**Comment by Kadirmertabdulharim** [comment]
> 

Win 10 64 bit hocam kodlama hakkında zerre birsey bilmediğim için sordumda rahatsız etmedim umarım iyi geceler.

**Comment by Kadirmertabdulharim** [comment]
> İşletim sistemin nedir dostum?
Win 10 64 bit hocam kodlama hakkında zerre birsey bilmediğim için sordumda rahatsız etmedim umarım iyi geceler

**Comment by Bora185** [comment]
Öncelikle https://www.python.org/downloads/ bu adresten en son python sürümünü (3.11.1) indirin. Kurulum sırasında "add to PATH" tarzı bir seçenek olması gerek. Onu işaretleyerek kurulum yapın Ardından https://git-scm.com/download bu adresten "git" komutunu kullanabilmemiz için git-scm indirin. Kurun. Windows PowerShell açın (arama kutusuna yazarak bulabilirsiniz) ve şu komutları sırayla yazın. 

```
git clone https://github.com/tingirifistik/Enough.git
cd Enough
pip3 install -r requirements.txt
python3 enough.py
```

**Comment by Kadirmertabdulharim** [comment]
> Öncelikle https://www.python.org/downloads/ bu adresten en son python sürümünü (3.11.1) indirin. Kurulum sırasında "add to PATH" tarzı bir seçenek olması gerek. Onu işaretleyerek kurulum yapın Ardından https://git-scm.com/download bu adresten "git" komutunu kullanabilmemiz için git-scm indirin. Kurun. Windows PowerShell açın (arama kutusuna yazarak bulabilirsiniz) ve şu komutları sırayla yazın.
> 
> ```
> git clone https://github.com/tingirifistik/Enough.git
> cd Enough
> pip3 install -r requirements.txt
> python3 enough.py
> ```

Tamamdır hocam yarın ilk işim denemek olacak daha iyi yerlere gelmeniz niyetiyle iyi geceler dilerim sağolun.

**Comment by Bora185** [comment]
Öncelikle https://www.python.org/downloads/ bu adresten en son python sürümünü (3.11.1) indirin. Kurulum sırasında "add to PATH" tarzı bir seçenek olması gerek. Onu işaretleyerek kurulum yapın Ardından https://git-scm.com/download bu adresten "git" komutunu kullanabilmemiz için git-scm indirin. Kurun. Windows PowerShell açın (arama kutusuna yazarak bulabilirsiniz) ve şu komutları sırayla yazın. 

```
git clone https://github.com/tingirifistik/Enough.git
cd Enough
pip3 install -r requirements.txt
python3 enough.py
```

**Comment by Bora185** [comment]
İyi geceler hocam.
