### ISSUE TITLE
Çoklu sms

### ISSUE THREAD

**Issue by Kadirmertabdulharim** [tingirifistik/Enough#28]
Selamlar ustam  Yeni eklenen 1 den fazla sms atma seçeneğini gördüm fakat nasıl kullanıldığını çözemedim mümkünse yardımcı olabilirmisiniz? Cihazım:win10 64x @tingirifistik @Bora185

**Comment by uwt00** [comment]
numaraları başında 90 olmadan bir txt belgesine alt alta yazıp kaydet sonrasında numara yazma ekranında belgenin adını yaz oluyor
