### ISSUE TITLE
Discord bota kurma

### ISSUE THREAD

**Issue by chinhock12** [tingirifistik/Enough#29]
Kanka bota kurma işlemi tam olarak nasıl yapılıyor

**Comment by Yimikami** [comment]
```
git clone https://github.com/tingirifistik/Enough.git
cd enough/bot
pip3 install -r requirements.txt
type nul > sms.py
```
Bot açılışta aynı dizin üzerinde 'sms.py' dosyası arıyor ve o dosyayı repodaki dosyayla karşılaştırıp ona göre güncelleme yapıyor.
Bu yüzden son satırdaki kod ile boş bir 'sms.py' dosyası oluşturabilirsin ya da enough klasöründeki 'sms.py' dosyasını bot klasörüne atabilirsin.
![image](https://user-images.githubusercontent.com/39545057/215094481-ae8089ed-147c-428a-9571-c0667398056c.png)

Ardından '**discord-enough.py**' dosyasını düzenleyerek **'TOKEN'** kısmına botun tokenini yazacaksın.


```
TOKEN = "(BOT TOKEN)"
```

Son olarak botu başlatıyoruz.
```
py discord-enough.py
```
