### ISSUE TITLE
discord bota kurmada yardım edermisin INC#0001

### ISSUE THREAD

**Issue by zevoesdios** [tingirifistik/Enough#30]
kral discordda bota kuramadım yardımcı olurmusun lütfen, şimdiden teşekkürler.

**Comment by Yimikami** [comment]
https://github.com/tingirifistik/Enough/issues/29#issuecomment-1406511665
Burada anlattım ancak yapamazsan discorddan ekledim, yardımcı olurum.

**Comment by mxhmmt** [comment]
@Yimikami kanka bana da yardımcı olur musun? matiz7#8536

**Comment by Kaosw2** [comment]
@Yimikami banada olursan sevinirim reis hENNESsy#8726
