### ISSUE TITLE
Heroku

### ISSUE THREAD

**Issue by TeaqariaWTF** [tingirifistik/Enough#4]
Merhabalar.
Herokuda  kurmaya çalışıyorum ama Bot Ücretsiz sürümü Göre ayarlanmış bu yüzden hata veriyor.yardımcı olur musunuz

**Comment by tingirifistik** [comment]
Düzelttim.

**Comment by TeaqariaWTF** [comment]
Hocam heroku da başarılı bir şekilde kurdum ama telegram botu çalışmıyor.
/start komutuna tepki vermiyor.
@tingirifistik

**Comment by tingirifistik** [comment]
Botu telegram kütüphanesi ile yeniden yazdım. Şimdi sorunsuz çalışır muhtemelen.

**Comment by burakdarama** [comment]
merhaba hocam. Sms gönderdiğimiz zaman gizli mi gönderiliyor? yani herhangi bir dava veya araştırma sonucu bizim gönderdiğimiz ortaya çıkar mı?

**Comment by tingirifistik** [comment]
bunun icin dava acacaklarini dusunmuyorum.
