### ISSUE TITLE
telegram botu

### ISSUE THREAD

**Issue by heyslenex** [tingirifistik/Enough#5]
telegram-enough dosyasında     sendMessage("Bu önemli şahsiyeti rahatsız etmek istemiyorum.\nFarklı telefon numarası yazınız!", id) bu şekilde satır var. numaraları nasıl blackliste ekliyoruz?

**Comment by tingirifistik** [comment]
` environ.get('SAHIP')`
Kısmına tel no yazarak yapabilirsiniz. (str olarak)

**Comment by heyslenex** [comment]
SAHIP yazan yere numara mı yazmam gerekiyor?

**Comment by tingirifistik** [comment]
`environ.get('SAHIP')` kismini tamamen silip bunun yerine tel no yazacaksin.

**Comment by heyslenex** [comment]
anladım hocam. Bir de telegram botu sms gönderiliyor tepkisi veriyor ama tamamlandı tepkisi gelmiyor bir de sms göndermiyor

**Comment by heyslenex** [comment]
dediğin gibi yaptım hocam fakat sms gelmeye devam ediyor

**Comment by tingirifistik** [comment]
Telefon numarasının başında +90 olmamalı ve string değer olmalı.
