### ISSUE TITLE
Hata

### ISSUE THREAD

**Issue by PrestijX** [tingirifistik/Enough#6]
Discord self botu kullanmaya çalıştığımızda böyle bir hata veriyor ve ayrıca Enough.py de olduğu gibi terminalde + - işaretleri renklenmiyor. Bir sorun daha bot çalışırken bir .sms daha gönderdiğimizde bunu görmüyor veya sıraya almıyor.

```
Traceback (most recent call last):
  File "C:\Users\User\Desktop\Enough-main\discord-selfbot-enough.py", line 59, in <module>
    sms = SendSms(telno)
          ^^^^^^^^^^^^^^
TypeError: SendSms.init() missing 1 required positional argument: 'mail'
```

**Comment by tingirifistik** [comment]
Hatayi hallettim. sms gonderirken yazdiginiz seyleri algilamaz. sms gonderiminin bitmesini beklemelisiniz.

**Comment by PrestijX** [comment]
C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py:1045: InsecureRequestWarning: Unverified HTTPS request is being made to host 'mobileapi.totalistasyonlari.com.tr'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

Bu seferde böyle bir hata mevcut.
