### ISSUE TITLE
Call Bomb Sorun

### ISSUE THREAD

**Issue by santiagocss** [tingirifistik/Enough#9]
2 siteden sonra devamı gelmiyor onlara da başarısız diyo 
![image](https://user-images.githubusercontent.com/36582849/212944528-32ddd4e3-a32e-41c9-88a8-6841b968e050.png)

**Comment by tingirifistik** [comment]
Tepki vermiyorsa biraz beklemen gerekiyor. Ayrıca şu an bende sadece `expressdekor.com` çalışmıyor.
